name: Bug Report
description: Reporte um bug no @meuorg/map-3d-deck
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por reportar um bug! Por favor, preencha as informações abaixo.

  - type: textarea
    id: description
    attributes:
      label: Descrição do Bug
      description: Uma descrição clara e concisa do que é o bug.
      placeholder: Descreva o bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Passos para Reproduzir
      description: Passos para reproduzir o comportamento
      placeholder: |
        1. Criar mapa com '...'
        2. Adicionar camada '...'
        3. Clicar em '...'
        4. Ver erro
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportamento Esperado
      description: O que você esperava que acontecesse?
      placeholder: Descreva o comportamento esperado...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Comportamento Atual
      description: O que realmente aconteceu?
      placeholder: Descreva o que aconteceu...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Código de Exemplo
      description: Se possível, inclua um exemplo mínimo que reproduza o problema
      render: typescript
      placeholder: |
        import { Map3D, createZoningLayer } from '@meuorg/map-3d-deck'

        const map = new Map3D({ container: 'map' })
        // ...

  - type: input
    id: version
    attributes:
      label: Versão do Pacote
      description: Qual versão do @meuorg/map-3d-deck você está usando?
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: node
    attributes:
      label: Versão do Node.js
      description: Qual versão do Node.js você está usando?
      placeholder: "20.10.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Sistema Operacional
      options:
        - macOS
        - Windows
        - Linux
        - Outro
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Navegador (se aplicável)
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Outro
        - N/A

  - type: textarea
    id: logs
    attributes:
      label: Logs de Erro
      description: Se houver mensagens de erro, cole-as aqui
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Informações Adicionais
      description: Qualquer outra informação relevante
